### ISSUE TITLE
log(int&) is ambiguous: g++-6 only

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#327]
#### Summary:

Stan code that takes the logarithm of an integer parses but does not compile in 2.11

#### Description:

Stan code that takes the logarithm of an integer parses but does not compile in 2.11

Here are the cases that fail with g++6 on Mac OS X:

* [x] `log()`
* [x] `exp()`
* [x] `log2()`
* [x] `log1p()`

#### Reproducible Steps:

```
transformed data {
  real sum_log;
  sum_log = 0;
  for (i in 1:2) sum_log = sum_log + log(i);
}
model {}
```

#### Current Output:

```
file166d5fc5ef52.cpp: In member function ‘void model166d2e654d2_log_namespace::model166d2e654d2_log::ctor_body(stan::io::var_context&, RNG&, std::ostream*)’:
file166d5fc5ef52.cpp:76:61: error: call of overloaded ‘log(int&)’ is ambiguous
                 stan::math::assign(sum_log, (sum_log + log(i)));
                                                             ^
```

#### Expected Output:

Nothing

#### Additional Information:

Wasn't happening with 2.10. Don't hold up the 2.11 release; I'll add 0.0 to the integer.

#### Current Version:
v2.11.0

**Comment by syclik** [comment]
This must have been with the vectorize-all pull request. This might actually pose a problem. Mind trying it out on any other unary function?

**Comment by bgoodri** [comment]
sqrt() works; exp() does not

**Comment by syclik** [comment]
I'm not seeing the issue from CmdStan. Do you have a `using std;` floating around somewhere in `stan_fit.hpp` or something like that?

**Comment by bgoodri** [comment]
No, only using std::vector

**Comment by bgoodri** [comment]
It works with g++-5 but not with g++-6

**Comment by syclik** [comment]
how do I recreate this locally? I was able to do it directly through C++ by using two using statements. CmdStan doesn't have this problem, so maybe we can work around this in RStan?

**Comment by bgoodri** [comment]
I can trigger it with cmdstan after updating all of the submodules to
develop

**Comment by syclik** [comment]
with g++-6? does it happen with g++-5?

(I'm wondering if clang++'s behavior on Mac is more like g++-5.)

**Comment by bgoodri** [comment]
g++-5 is fine; g++-6 is not. clang++ works iff -stdlib=libc++

**Comment by syclik** [comment]
Do a lot of people use g++-6? Is it stable? Is that compiler a CRAN requirement? Are you using a release version of the compiler?

**Comment by bgoodri** [comment]
It has been released as stable since April. CRAN has many test machines
that use g++-6, although I don't think we have any tests that would trigger
failures like this. I found it from an rstanarm model.

**Comment by syclik** [comment]
Ok. Any way you can install that compiler on the machine in your office? I'm try to hunt it down if I can log in.

**Comment by bgoodri** [comment]
Windows uses 4.9, which seems to be fine. g++-6 just doesn't know whether
to use double, float, or long double when log (or other C++ function) is
given an int:

/tmp/SU/log.hpp:71:56: error: call to 'log' is ambiguous
                stan::math::assign(sum_log, (sum_log + log(i)));
                                                       ^~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/cmath:373:5:
note: candidate function [with _Tp = int]
    log(_Tp __x)
    ^
stan/lib/stan_math/stan/math/prim/mat/fun/log.hpp:32:5: note: candidate
function [with T = int]
    log(const T& x) {
    ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:17: note: candidate
function
__MATHCALL_VEC (log,, (_Mdouble_ __x));
                ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/cmath:361:3:
note: candidate function
  log(float __x)
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/cmath:365:3:
note: candidate function
  log(long double __x)
  ^
stan/lib/stan_math/stan/math/rev/scal/fun/log.hpp:50:16: note: candidate
function
    inline var log(const var& a) {
               ^
1 error generated.
make/models:9: recipe for target '/tmp/SU/log' failed

**Comment by syclik** [comment]
What about the Linux box?

**Comment by bgoodri** [comment]
It isn't set up yet

**Comment by bob-carpenter** [comment]
One approach would be to cast the argument to double
before applying log in the vectorization.  

Perhaps longer term we should define our own wrappers
for the standard library functions so that we can control
this better.  That is, define a stan::math::log(double) function
and make that our translation target rather than std::double.

If there's ambiguity between int->double and int->var, we're going
to be in trouble elsewhere.  We want that to go to double
wherever possible.

- Bob

**Comment by bgoodri** [comment]
I think part of the problem is that we have a log (and exp) specialization
only for Eigen types. For sqrt, sinh, etc. we have no specializations at
all and it compiles fine.

**Comment by bob-carpenter** [comment]
That should be an easy fix. We don't need any
specializations for Eigen types other than the ones
in the vectorization code.

- Bob

**Comment by bgoodri** [comment]
It is correct that the unary vectorized functions are not exposed to the Stan language in 2.11?

**Comment by syclik** [comment]
That is correct. Only the ones that were vectorized by hand in the past.

**Comment by bob-carpenter** [comment]
So we need to 

1.  remove the redundant definitions from stan-dev/math

2.  add the vectorization signatures to stan-dev/stan

For (2), there's the question of how deep to declare things because
we iterate the signatures exhaustively in the function symbol table.

- Bob

**Comment by bob-carpenter** [comment]
Actually, there aren't redundant declarations for log like I suspected.  I don't see any `log()` or `exp()` specializatiosn for Eigen types in the current develop branch of stan-dev/math.  There's just the case to support vectorization in `math/prim/mat/fun/log.hpp` that isn't specialized for Eigen types any more than any of the other functions.

**Comment by bgoodri** [comment]
Still broken
```
/tmp/SU/log_int/log_int.hpp: In member function ‘void log_int_model_namespace::log_int_model::ctor_body(stan::io::var_context&, RNG&, std::ostream*)’:
/tmp/SU/log_int/log_int.hpp:71:61: error: call of overloaded ‘log(int&)’ is ambiguous
                 stan::math::assign(sum_log, (sum_log + log(i)));
                                                             ^
In file included from /usr/include/features.h:364:0,
                 from /usr/include/stdint.h:25,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h:9,
                 from stan/lib/stan_math/stan/math/memory/stack_alloc.hpp:6,
                 from stan/lib/stan_math/stan/math/rev/core/autodiffstackstorage.hpp:4,
                 from stan/lib/stan_math/stan/math/rev/core.hpp:4,
                 from stan/lib/stan_math/stan/math/rev/mat.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:4,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /tmp/SU/log_int/log_int.hpp:3,
                 from <command-line>:0:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:1: note: candidate: double log(double)
 __MATHCALL_VEC (log,, (_Mdouble_ __x));
 ^
In file included from stan/lib/stan_math/lib/boost_1.60.0/boost/config/no_tr1/cmath.hpp:21:0,
                 from stan/lib/stan_math/lib/boost_1.60.0/boost/math/tools/config.hpp:19,
                 from stan/lib/stan_math/stan/math/rev/core/var.hpp:7,
                 from stan/lib/stan_math/stan/math/rev/core/gevv_vvv_vari.hpp:5,
                 from stan/lib/stan_math/stan/math/rev/core.hpp:12,
                 from stan/lib/stan_math/stan/math/rev/mat.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:4,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /tmp/SU/log_int/log_int.hpp:3,
                 from <command-line>:0:
/usr/include/c++/6/cmath:373:5: note: candidate: constexpr typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, double>::__type std::log(_Tp) [with _Tp = int; typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, double>::__type = double]
     log(_Tp __x)
     ^~~
/usr/include/c++/6/cmath:365:3: note: candidate: constexpr long double std::log(long double)
   log(long double __x)
   ^~~
/usr/include/c++/6/cmath:361:3: note: candidate: constexpr float std::log(float)
   log(float __x)
   ^~~
In file included from stan/lib/stan_math/stan/math/rev/scal/fun/grad_inc_beta.hpp:10:0,
                 from stan/lib/stan_math/stan/math/rev/scal.hpp:49,
                 from stan/lib/stan_math/stan/math/rev/arr.hpp:9,
                 from stan/lib/stan_math/stan/math/rev/mat.hpp:10,
                 from stan/lib/stan_math/stan/math.hpp:4,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /tmp/SU/log_int/log_int.hpp:3,
                 from <command-line>:0:
stan/lib/stan_math/stan/math/rev/scal/fun/log.hpp:50:16: note: candidate: stan::math::var stan::math::log(const stan::math::var&)
     inline var log(const var& a) {
                ^~~
In file included from stan/lib/stan_math/stan/math/prim/mat.hpp:103:0,
                 from stan/lib/stan_math/stan/math/rev/mat.hpp:9,
                 from stan/lib/stan_math/stan/math.hpp:4,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /tmp/SU/log_int/log_int.hpp:3,
                 from <command-line>:0:
stan/lib/stan_math/stan/math/prim/mat/fun/log.hpp:36:5: note: candidate: typename stan::math::apply_scalar_unary<stan::math::log_fun, T>::return_t stan::math::log(const T&) [with T = int; typename stan::math::apply_scalar_unary<stan::math::log_fun, T>::return_t = double]
     log(const T& x) {
     ^~~
make/models:9: recipe for target '/tmp/SU/log_int/log_int' failed
make: *** [/tmp/SU/log_int/log_int] Error 1
goodrich@T540p:/opt/cmdstan$ cat stan/lib/stan_math/stan/math/prim/mat/fun/log.hpp 
#ifndef STAN_MATH_PRIM_MAT_FUN_LOG_HPP
#define STAN_MATH_PRIM_MAT_FUN_LOG_HPP

#include <stan/math/prim/mat/vectorize/apply_scalar_unary.hpp>
#include <cmath>

namespace stan {
  namespace math {

    /**
     * Structure to wrap log() so that it can be vectorized.
     * @param x Variable.
     * @tparam T Variable type.
     * @return Natural log of x.
     */
    struct log_fun {
      static double fun(int x) {
        return std::log(static_cast<double>(x));
      }

      template <typename T>
      static inline T fun(const T& x) {
        using std::log;
        return log(x);
      }
    };

    /**
     * Vectorized version of log().
     * @param x Container.
     * @tparam T Container type.
     * @return Natural log applied to each value in x.
     */
    template <typename T>
    inline typename apply_scalar_unary<log_fun, T>::return_t
    log(const T& x) {
      return apply_scalar_unary<log_fun, T>::apply(x);
    }

  }
}

#endif
```

**Comment by bob-carpenter** [comment]
Given the enable_if, it looks like you're running C++11, too,
and it looks like they provide a template instantiation tailored
to integers.

... 

> /usr/include/c++/6/cmath:373:5: note: candidate: constexpr typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, double>::__type std::log(_Tp) [with _Tp = int; typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, double>::__type = double]
>      log(_Tp __x)
>      ^~~

...

**Comment by bgoodri** [comment]
g++-6 uses GNU's version of the C++14 standard by default

https://gcc.gnu.org/gcc-6/changes.html

**Comment by bob-carpenter** [comment]
There seems to be a problem with the way g++-6 catches exceptions, not just for me:

http://stackoverflow.com/questions/10276798/gdb-not-catching-stdout-of-range-thrown-by-vector

**Comment by bob-carpenter** [comment]
This also seems to be relevant:

http://www.dribin.org/dave/blog/archives/2006/02/10/gcc_exception_bug/

**Comment by bgoodri** [comment]
Does this have anything to do with the int thing?

**Comment by bob-carpenter** [comment]
Only insofar as it causes the integrate_ode_bdf tests to fail
with g++-6, so I can't run all the tests without commenting
some out (as I did in the pushed code, with FIXME(carpenter)
attached to the commented out bits and notes in the issue.

It may very well be calling the C library, which may be masked
from having its exceptions visible.  I don't even understand
the visibility business.

Here's one more note:

https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/CppRuntimeEnv/Articles/SymbolVisibility.html

but that only seems relevant to Xcode and dates back to gcc4.
I can't find anything about bugs in g++6 for symbol visibility,
but I think we're way out on the bleeding edge here.

Would you mind pulling down my branch and uncommenting some
of the tests in 

test/unit/math/rev/mat/functor/integrate_ode_bdf_prim_test.cpp

and seeing if they'll pass in your Linux version?  If so, I won't
be too worried because nobody's going to be using g++6 on the Mac.

- Bob

**Comment by bgoodri** [comment]
./runTests.py test/unit/math/rev/mat/functor/integrate_ode_bdf_prim_test.cpp

passes after uncommenting the FIXMEs

**Comment by bgoodri** [comment]
Actually, all of test/unit passes.

**Comment by bob-carpenter** [comment]
Thanks, @bgoodri.  Would you mind testing again now that I uncommented the failing tests?

In any case, even if the remaining tests indicated in #348 still fail, we can merge this, because everything passes for me with g++6 if I comment them out.

**Comment by bob-carpenter** [comment]
That's great news.  

How do you run the tests so quickly?  They take 77 minutes on
my Mac running four cores (about 250 minutes of compute time).

- Bob

**Comment by bgoodri** [comment]
test/unit/math/rev/mat/functor/integrate_ode_bdf_{prim,rev}_test.cpp are
fine in 11e766b

**Comment by bob-carpenter** [comment]
They fail on Mac OS X version:

g++-mp-6 (MacPorts gcc6 6.1.0_0) 6.1.0

But I think that's OK, because not many people are going to
be using g++6 on Mac OS X.

**Comment by bgoodri** [comment]
It is a separate issue regardless. Do you get the same failures with
clang++ in C++11 mode?

**Comment by bob-carpenter** [comment]
Everything passes with 

  clang++ -std=c++11 ...

Is that how I should be checking?

**Comment by bgoodri** [comment]
Yeah, or there is a C++11 flag that you can set to true in make/local

**Comment by bob-carpenter** [comment]
Thanks.

I set the option in make/local as part of the CC= bit.  I'm
not very good at reading these makefiles (but did figure out
the syntax-only compile from our test makefile [comments] so I could
quickly debug warnings in g++6).

- Bob

**Comment by bob-carpenter** [comment]
Fixed in pull #349
