### PR TITLE
#include <stdexcept>

### LINKED ISSUE #223: make stan/math/prim/scal/meta/container_view.hpp-test fails
## Bug Report

__Version__
develop

__Description__
test failure

__Steps__
`make stan/math/prim/scal/meta/container_view.hpp-test`

__Output__
```
In file included from <command-line>:0:0:
./stan/math/prim/scal/meta/container_view.hpp: In member function ‘stan::math::container_view<stan::math::dummy, T2>::scalar_t stan::math::container_view<stan::math::dummy, T2>::operator[](int) const’:
./stan/math/prim/scal/meta/container_view.hpp:82:17: error: ‘out_of_range’ is not a member of ‘std’
           throw std::out_of_range("can't access dummy elements.");
                 ^
make/tests:64: recipe for target 'stan/math/prim/scal/meta/container_view.hpp-test' failed
make: *** [stan/math/prim/scal/meta/container_view.hpp-test] Error 1
```

__Expected Output__
Nothing

__Additional Information__
Works with clang++ and g++-5 but not g++-4.9

### PR DESCRIPTION
**Pull request by bgoodri**
It's needed in `stan/math/prim/scal/meta/container_view.hpp`.

Closes #223

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Looks good.  I pushed a fix to the lint issue and it should be ready to merge when it passes tests.
