### PR TITLE
concurrent map_rect, fixes #822

### LINKED ISSUE #822: concurrent map_rect
#### Summary:
Make map_rect use the threading facilities of stan-math

#### Description:
Enable within-chain parallelization on a given machine using c++11 facilities. The number of concurrent threads should be controllable at runtime.

#### Reproducible Steps:
NA

#### Current Output:
Functions calling map_rect get a ragged arrays as output.

#### Expected Output:
Nothing will change wrt to the output of the map_rect function (it will just be faster).

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

### PR DESCRIPTION
**Pull request by wds15**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py test/unit`
- [X] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below

#### Summary:
Replace map_rect_serial with map_rect_concurrent which is threaded if STAN_THREADS is defined.

#### Intended Effect:
Allow for within-chain parallelization using threads.  Threading is enabled if `STAN_THREADS` is defined at compile time. The number of concurrent tasks being executed is defined by the runtime environment variable `STAN_NUM_THREADS` in the following way:

- if not defined, only a single thread is used (no threading)
- if set to a number greater than 0, then at most this many number of threads will be run concurrently, see notes below
- if set to -1, then the hardware concurrency will be used
- any other value will lead to the use of only a single process

The implementation uses the `async` facility of C++11. All defined jobs are chunked into as many threads are supposed to be used and per chunk a `async` call is made. Hence, the *maximal* number of concurrent jobs is defined by `STAN_NUM_THREADS`, but how many are actually being run concurrently is up to the implementation of `async` provided by the compiler. There is no further control possible.

#### How to Verify:
1. Define in `make/local` `CXXFLAGS+=-DSTAN_THREADS`
2. Run `export STAN_NUM_THREADS=-1`
3. Run the two tests `test/unit/math/{prim, rev}/mat/functor/map_rect_concurrent_test.cpp`

#### Side Effects:
None.

#### Documentation:
In the code. More?

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sebastian Weber

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
@seantalts The tests on travis fail presumably due to the very outdated ubuntu 14.04 LTS. Can we test MPI and multithreading on the Jenkins box? That would require to have a thread-capable clang++ (or g++) to run the unit test suite. If the answer is yes...could you help with setting this up (or guide me what I need to put into this pull to make that work)? Thanks!

**Comment by seantalts** [comment]
Hm, which version(s) of which do you want installed? You can see here how they get installed:
https://github.com/stan-dev/math/blob/develop/.travis.yml#L12
First linux_clang is defined and then it's sort of included in each of the tests like so:
https://github.com/stan-dev/math/blob/develop/.travis.yml#L31

**Comment by wds15** [comment]
Travis is just not working for this threading thing as it looks like. With clang things do not compile due to this atexit problem and g++ produces binaries which crash. This is why I was wondering about the Jenkins box at Columbia. Can we use that for testing threading?

**Comment by seantalts** [comment]
I think it's probably important to dig into why it's "just not working" - at least to be able to tell our users which compiler versions on which OSes will support it. Do you have any clues towards this so far? It might be useful to try a later clang or gcc version and see if that works?

**Comment by wds15** [comment]
Hmmm... we could try a later g++ version on travis and see if that works - assuming its ok to switch the travis g++ to a later version.

I agree in that it would be good to debug this a bit. For this I need to install a virtual instance of that ubuntu. In any case we need a platform where to can run the tests on. Checking what travis offers seems to suggest that we could use g++5, g++6 & g++7. Right now we use g++ 4.9 - should I try g++5? Would that be an option? I know that g++4.9 is probably chosen, because this is close to the Rtools g++ if I recall right. Would in that case g++5 still be an option to use and travis - and if so should I use it for all tests or just the threaded one?

Sorry for this mess!

**Comment by seantalts** [comment]
Yeah, RTools is gcc 4.9.3, so if it doesn't work on there, we will likely have different requirements for threading and/or MPI than our standard release. Right now we don't test math on Windows at all, but maybe we should switch to that instead of Travis (since Ubuntu + gcc-4.9.3 is not really our target). 

I think a decent path forward could be to figure out which compilers this works under and just run these (currently failing) tests under those compilers. Then we have to change our supported compilers page to show which features work under which compilers and OS combinations (and make sure we test the ones we say we support). This is going to get pretty hairy already with MPI, GPU, and threading all having different requirements. @syclik what do you think about this path?

**Comment by syclik** [comment]
@seantalts: that sounds good. (I thought I suggested that a while back, but might have been on a different thread.) It'll take some work, as you've clearly noted. Maybe we can split up the tasks so it's not all on one person?

**Comment by seantalts** [comment]
Cool, just wanted to make sure that was the general MO for these things - I think we've both expressed some chagrin at the increasing cross-compiler shenanigans, but hopefully we can find ways to mitigate that.

**Comment by sakrejda** [comment]
@wds15 @syclik  I ran this prim/rev with some compilers I have installed on Ubuntu, probably ones you have tested already (details below).  All of them using the non-clang standard libraries.  What would actually be helpful in terms of getting this in?  It looks like there might be issues with why things are failing on some Ubuntu clang versions, that's easy for me to install so... which ones do you want tested? 4.8 is probably too old, though that's what the ubuntu rtools ppa provides for my Ubuntu version (I miss Gentoo/portage where this was all really easy...).

```
g++ (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

clang++-5.0 --version
clang version 5.0.0-3 (tags/RELEASE_500/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

g++-4.8 --version
g++-4.8 (Ubuntu 4.8.5-4ubuntu6) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

- g++-7.2.0 works
- clang++-5.0 works
- g++-4.8 fails because it can't find `std::isfinite` and `std::isinf`, and also complains about `__builtin_isnan` being missing even though boost expects it

**Comment by wds15** [comment]
Note that I have just 30min ago merged fixes for the threading stuff into develop which I also merged into this branch just a few moments ago. These fixes should dramatically improve the compilers which we can now run this on.

So if you have used the old stuff... could you run these tests again, please?

To summarize my findings:

- ubuntu 14.04 with clang is problematic. Ubuntu 16.04 should work (@bgoodri said so)
- g++ >= 4.9 should be ok
- clang 3.8 is ok (just not on that old ubuntu 14.04)
- clang 4 is probably safer to use (if used with libc++ 4.0)

And as I said, the just merged fixed for the threading are important to make most compilers happy.

This should actually work on windows which is almost a miracle.

**Comment by sakrejda** [comment]
g++-4.8 still fails, I'll check 4.9.3 since that's Rtools

**Comment by sakrejda** [comment]
Welp, the official sources for gcc-4.9.3 don't build with g++-7.2.0 or g++ 4.8 so... is that something we _should_ be testing? If so I'll put in the effort to figure out how to run tests with it but so far no source for g++ 4.9

**Comment by sakrejda** [comment]
Looking into it but g++ 4.9.4 on Ubuntu fails (for this test not for non-threading tests):

```
g++-4.9 -Wall -I . -isystem lib/eigen_3.3.3 -isystem lib/boost_1.66.0 -isystem lib/cvodes-3.1.0/include -isystem lib/idas-2.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -DSTAN_THREADS -pthread -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O3 -DNO_FPRINTF_OUTPUT -pipe   -o test/unit/math/prim/mat/functor/map_rect_concurrent_test test/unit/math/prim/mat/functor/map_rect_concurrent_test.o lib/gtest_1.7.0/src/gtest_main.cc lib/gtest_1.7.0/src/gtest-all.o
test/unit/math/prim/mat/functor/map_rect_concurrent_test.o: In function `testing::AssertionResult testing::internal::CmpHelperFloatingPointEQ<float>(char const*, char const*, float, float)':
map_rect_concurrent_test.cpp:(.text._ZN7testing8internal24CmpHelperFloatingPointEQIfEENS_15AssertionResultEPKcS4_T_S5_[_ZN7testing8internal24CmpHelperFloatingPointEQIfEENS_15AssertionResultEPKcS4_T_S5_]+0x130): undefined reference to `testing::internal::StringStreamToString(std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*)'
map_rect_concurrent_test.cpp:(.text._ZN7testing8internal24CmpHelperFloatingPointEQIfEENS_15AssertionResultEPKcS4_T_S5_[_ZN7testing8internal24CmpHelperFloatingPointEQIfEENS_15AssertionResultEPKcS4_T_S5_]+0x13f): undefined reference to `testing::internal::StringStreamToString(std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*)'
map_rect_concurrent_test.cpp:(.text._ZN7testing8internal24CmpHelperFloatingPointEQIfEENS_15AssertionResultEPKcS4_T_S5_[_ZN7testing8internal24CmpHelperFloatingPointEQIfEENS_15AssertionResultEPKcS4_T_S5_]+0x15a): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
test/unit/math/prim/mat/functor/map_rect_concurrent_test.o: In function `testing::AssertionResult testing::internal::CmpHelperEQ<long, int>(char const*, char const*, long const&, int const&)':
map_rect_concurrent_test.cpp:(.text._ZN7testing8internal11CmpHelperEQIliEENS_15AssertionResultEPKcS4_RKT_RKT0_[_ZN7testing8internal11CmpHelperEQIliEENS_15AssertionResultEPKcS4_RKT_RKT0_]+0x63): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
collect2: error: ld returned 1 exit status
make/tests:16: recipe for target 'test/unit/math/prim/mat/functor/map_rect_concurrent_test' failed
make: *** [test/unit/math/prim/mat/functor/map_rect_concurrent_test] Error 1
make -j4 test/unit/math/prim/mat/functor/map_rect_concurrent_test failed
exit now (04/29/18 16:43:31 EDT)

```

**Comment by wds15** [comment]
Have you removed the gtest binary? A make clean does not wipe that out.

The tests on travis do test on linux gcc 4.9 and on macos high sierra I am using the clang from Apple. So I would expect the g++ to work.

**Comment by sakrejda** [comment]
4.9.4 is failing with a linker error due to something wrong with gtest, nothing to do with the threading code (directly anyway).  The tests pass if I remove the EXPECT_* and calculate the tests manually.

**Comment by wds15** [comment]
Odd... as I say, on Travis gcc 4.9 works fine. That is why I was suspecting your installation not being clean. Travis runs 14.04 LTS ubuntu, so I would expect that you are good.

**Comment by bgoodri** [comment]
I fixed the gtest thing in
https://github.com/stan-dev/math/pull/849/commits/77774a01589f5bf981c7f81cff06b3ad85b2e32f

**Comment by wds15** [comment]
...whenever that gets merged...

**Comment by sakrejda** [comment]
yeah, after `make clean-all` the binaries are gone and other tests do build fine, _and_ the values are correct, it's just the EXPECT_* statements that create linker errors, so it's really only relevant if somebody runs threading tests on Ubuntu with g++-4.9 (plus some other factor apparently).  Up to you if we ignore it or not.

**Comment by sakrejda** [comment]
Real question is: are there tests we _should_ still run prior to merging this? (since other easily available and recent/standard Ubuntu compilers work).  I have access to other machines.

**Comment by sakrejda** [comment]
Also: are we down to tests or is there other stuff to be done?

**Comment by sakrejda** [comment]
Yes review is different, I was assuming you were wanting @bob-carpenter to do review since he's tagged.  Do you want a second reviewer? I can see some stuff to clean up but I don't need to duplicate work.

**Comment by wds15** [comment]
Oh, by no means this has to be reviewed by @bob-carpenter . I guess that github suggested him. So if you have the time to do the review, go ahead. As we anyway need to run this by the stan meetings, we can get him aligned on Thursday.

Just two notes wrt to decisions which I took (and you may challenge):

- the code to obtain from the environment variable STAN_NUM_THREADS the number of threads should probably be split out either now or at some later point into a separate function.
- it could make sense to expose the combine thing as template argument. This would allow the MPI implementation to use this map_rect_concurrent, but let the function return outputs in a format suitable for transfer over MPI.

I did not do these two things in order to expedite inclusion into stan-math as I think this is a big deal to get within-chain parallelization with just threads (but you may judge differently).

**Comment by sakrejda** [comment]
Ok, I'll review.

**Comment by sakrejda** [comment]
@wds15 it was easier to make a branch and test it rather than suggest stuff.  If you're ok with this I'll merge it into your branch: https://github.com/sakrejda/math/blob/f70faec8467d23b2fe42702271c1b1c6a48010c5/stan/math/prim/mat/functor/map_rect_concurrent.hpp

File: stan/math/prim/mat/functor/map_rect_concurrent.hpp [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+    if (j == 0)
+      world_output.resize(chunk_result[0].rows(),
+                          num_jobs * chunk_result[0].cols());
+
+    for (const auto& job_result : chunk_result) {
+      const int num_job_outputs = job_result.cols();
+      world_f_out.push_back(num_job_outputs);
+
+      if (world_output.cols() < offset + num_job_outputs)
+        world_output.conservativeResize(Eigen::NoChange,
```
[the remark this answers is not in the document]
Comment (wds15) [reply stan/math/prim/mat/functor/map_rect_concurrent.hpp]: What I have in mind to do eventually is to make `CombineF` a configurable type. Right now this type is hard-coded inside the function. However, if this is an extra template argument, then the MPI thing could use this function just as is, but use a combine function which does not insert things into the AD stack, but essentially just returns the ragged output matrix structure... maybe we leave this for another day.

File: stan/math/prim/mat/functor/map_rect_concurrent.hpp [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+    if (j >= num_jobs_min && num_jobs_per_thread_remainder > 0) {
+      job_end++;
+      num_jobs_per_thread_remainder--;
+    }
+    if (j == num_threads - 1)
+      job_end = num_jobs;
+    // we only defer the first chunk such that the main thread is not
+    // blocking if we use threading
+    futures.emplace_back(std::async(j == 0 ? std::launch::deferred :
+#ifndef STAN_THREADS
```
[the remark this answers is not in the document]
Comment (wds15) [reply stan/math/prim/mat/functor/map_rect_concurrent.hpp]: Your way of coding this up is cleaner, so let's go with that. I would prefer to call the `n_threads` function `get_num_threads`; does that make sense to you? This would be more consistent with the `num` prefix and discriminate the function from the variable.

Also... I forgot to use the `nullptr` for the msgs argument of the function.

**Comment by wds15** [comment]
Hmm... maybe to keep reviewer and coder role a bit more separate, let me merge your changes with the few changes I think are needed. Then you can again review.

File: stan/math/prim/mat/functor/map_rect_concurrent.hpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (wds15) [reply stan/math/prim/mat/functor/map_rect_concurrent.hpp]: One more note: The way you have setup things will have the main process do num_jobs_per_thread and the second thread must calculate num_jobs_per_thread+1 tasks. However, since we collect things in order the second thread will block until done. Thus, I think it is better to move the excess jobs to the end of queue. This is probably minor in most cases, but could yield better performance, I think.

File: stan/math/prim/mat/functor/map_rect_concurrent.hpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (sakrejda) [reply stan/math/prim/mat/functor/map_rect_concurrent.hpp]: Sounds good.

File: stan/math/prim/mat/functor/map_rect_concurrent.hpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (sakrejda) [reply stan/math/prim/mat/functor/map_rect_concurrent.hpp]: Ok, that makes sense.   I think that's a one line change.

**Comment by sakrejda** [comment]
Thanks for adding doc.  Assuming the checks complete and tests pass (with varying numbers of threads so we didn't jointly goof on indexing) please go ahead and push the merge button.  It's cool that the CombineF/ReduceF things end up being agnostic to how the actual work is done.
